import type { NextPage } from 'next';
import dynamic from 'next/dynamic';
import Head from 'next/head';

const Editor = dynamic(() => import('../components/Editor'), { ssr: false });

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Lmao</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Editor />
    </div>
  );
};

export default Home;
