import type { NextPage } from 'next'
import Head from 'next/head'
import styled from 'styled-components'

const Test = styled.p`
  color: red;
`

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Lmao</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Test>lmao</Test>
    </div>
  )
}

export default Home
